### ISSUE TITLE
adjust lib search order

### ISSUE THREAD

**Issue by bebbo** [bebbo/gcc#104]
@githubaf: based on reviewing your pull request.

passing `--verbose` to the linker reveals the search pass. And now I'm thinking that the search order should be different:

the outermost criterion should be the data model, to chose a lib with the standard data model as the last option.

This requires also changes in https://github.com/amiga-gcc, https://github.com/libnix and https://github.com/clib2 (newlib should be covered since the multilib setting is evaluated)

**Comment by bebbo** [comment]
the new correct folder for m68881 libs would be:
```
/lib/libm020/libm881/
/lib/libb/libm020/libm881/
/lib/libb32/libm020/libm881/
```

**Comment by githubaf** [comment]
I can look tomorrow.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: bebbo <notifications@github.com> Datum: 08.07.19  12:46  (GMT+01:00) An: bebbo/gcc <gcc@noreply.github.com> Cc: githubaf <selco@t-online.de>, Mention <mention@noreply.github.com> Betreff: Re: [bebbo/gcc] adjust lib search order (#104) the new correct folder for m68881 libs would be:
/lib/libm020/libm881/
/lib/libb/libm020/libm881/
/lib/libb32/libm020/libm881/


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bebbo/gcc/issues/104?email_source=notifications\u0026email_token=AGY4WQ472FZ2Y2WBWCMD6ULP6MLKBA5CNFSM4H56JIBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZMWVSA#issuecomment-509176520",
"url": "https://github.com/bebbo/gcc/issues/104?email_source=notifications\u0026email_token=AGY4WQ472FZ2Y2WBWCMD6ULP6MLKBA5CNFSM4H56JIBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZMWVSA#issuecomment-509176520",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
