### ISSUE TITLE
Does -pthread work?

### ISSUE THREAD

**Issue by arczi84** [bebbo/gcc#122]
Cmake detects it:

> Check if compiler accepts -pthread - yes

but when compiling :

> m68k-amigaos-g++: error: unrecognized command line option '-pthread'

**Comment by bebbo** [comment]
that's not a gcc command line option.

do you mean `-lpthread` ?

**Comment by MBeijer** [comment]
-pthread works in some cases, I think it assumes that pthread is built-in
to libc or something like that

**Comment by bebbo** [comment]
> 
> -pthread works in some cases, I think it assumes that pthread is built-in to libc or something like that

There are gcc versions which support tha command line option.
This one does not support it.
```
stefan@Thinky:~/amiga-gcc/tickets/ccm$ m68k-amigaos-gcc -O2 m.c x.c -o m -pthread
m68k-amigaos-gcc: error: unrecognized command line option '-pthread'
stefan@Thinky:~/amiga-gcc/tickets/ccm$ m68k-amigaos-g++ -O2 m.c x.c -o m -pthread
m68k-amigaos-g++: error: unrecognized command line option '-pthread'
```

**Comment by arczi84** [comment]
Can it be not detected for US then?

**Comment by bebbo** [comment]
stop using cmake^^ use something reasonable ;-)

**Comment by MBeijer** [comment]
CMake is reasonable. There's a reason it's basically the industry standard
today.

**Comment by bebbo** [comment]
> 
> ... industry standard ... .

that explains everything ...

**Comment by bebbo** [comment]
please test

**Comment by arczi84** [comment]
Yeah, works now

**Comment by githubaf** [comment]
Could you provide an example to play around with?Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: arczi84 <notifications@github.com> Datum: 09.10.19  11:50  (GMT+01:00) An: bebbo/gcc <gcc@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [bebbo/gcc] Does -pthread work? (#122) Yeah, works now

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bebbo/gcc/issues/122?email_source=notifications\u0026email_token=AGY4WQ6OG7ZSADRH3PTKGHTQNWSO5A5CNFSM4I6QDWQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAXKJIQ#issuecomment-539927714",
"url": "https://github.com/bebbo/gcc/issues/122?email_source=notifications\u0026email_token=AGY4WQ6OG7ZSADRH3PTKGHTQNWSO5A5CNFSM4I6QDWQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAXKJIQ#issuecomment-539927714",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by arczi84** [comment]
It only appears to me with devilutionX .

https://github.com/diasurgical/devilutionX

śr., 9 paź 2019, 14:33 użytkownik githubaf <notifications@github.com>
napisał:
