### ISSUE TITLE
Optimizer questions

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#54]
Some general questions:

1) I saw the compiler generate a mulu.l instruction
for
```
	void  putPixel320(int16 x, int16 y, byte drawMask, byte color, byte priority, byte control) const {
		// Set pixel for visual, priority and control map directly, those are not upscaled
		const uint offset =  y * 320  + x;

		if (drawMask & GFX_SCREEN_MASK_VISUAL) {
			_displayScreen[offset] = color;
		}
		if (drawMask & GFX_SCREEN_MASK_PRIORITY) {
			_priorityScreen[offset] = priority;
		}
		if (drawMask & GFX_SCREEN_MASK_CONTROL) {
			_controlScreen[offset] = control;
		}
	}
```
With -Ofast and -m68020-60

I don't know if mulu is _that_ fast on 68030, but shouldn't it be faster to do two shifts instead: 

```
	void  REGPARM putPixel320(int16 x, int16 y, byte drawMask, byte color, byte priority, byte control) const {
		// Set pixel for visual, priority and control map directly, those are not upscaled
		const uint offset = ((uint)y  << 8)  + ((uint)y << 6) + x;
         ...
	}
```

I was somehow expecting the optimizer to do this kind of optimization on its own.

2) byte and short stack arguments are both using move.l to be push/popped onto the stack... isn't that suboptimal ?

2) If I use uint16 in above example,  the compiler will extend x and y no longer using ext.l, but instead
and.l 0xFFFF, d0 
and.l 0xFFFF, d1
instead (which is somehow expected as ext.l does signed-extend).
But is that the most effective way? I would have expected the 0xFFFF  to be placed into some temp. register instead of using it twice as immediate argument. Or  maybe some other more efficient method even.
It seems the need to use and.l is a side effect of passing x and y as longwords on the stack, so x an y are popped off the stack with potentially garbage in the upper 16 bits.

This is all C++ code and the functions mentioned above are member functions.

**Comment by mheyer32** [comment]
I think, to answer my own question, with -m68020-60 the compiler prefers mulu over additions.
I guess, the 060 can do mulu much faster  than 020/030? 

Could there be any compiler switch that would allow me to say "In case of speed try to optimize for 030, but still don't use functions not available on 060"? I'd rather optimize for speed on the slower machine.

**Comment by bebbo** [comment]
> 1. I saw the compiler generate a mulu.l instruction

gcc already determines if shifts/adds are faster than a multiplication or not.
This is based of the present instruction costs. And these are not accurate.
I tuned these costs for the mc68000 but not yet for higher processors.

> 2. byte and short stack arguments are both using move.l to be push/popped onto the stack... isn't that suboptimal ?

that's part of the calling convention. changing this would break the compatibility to existing code. Plus there is little or no gain from long to word. pushing bytes will lead to odd sp addresses and is a no go.

> 3. If I use uint16 in above example, the compiler will extend x and y no longer using ext.l, but instead
and.l 0xFFFF, d0

ext.l would be wrong. Depending on the cost information the compiler choses the instruction. Let's have a look:
```
extern unsigned short faa();
unsigned foo(unsigned short x) {
  return x * 320 + faa();
}
```

`-Os -fomit-frame-pointer -m68000` favors shorter code, thus mulu is used:
```
_foo:
        move.l d2,-(sp)
        move.l 8(sp),d2
        jsr _faa
        mulu.w #320,d2
        and.l #65535,d0
        add.l d2,d0
        move.l (sp)+,d2
        rts
```
`-O2 -fomit-frame-pointer -m68000` will use shift and add:
```
_foo:
        move.l d2,-(sp)
        move.l 8(sp),d2
        jsr _faa
        and.l #65535,d2
        move.l d2,d1
        lsl.l #2,d1
        add.l d2,d1
        lsl.l #6,d1
        and.l #65535,d0
        add.l d1,d0
        move.l (sp)+,d2
        rts
```
`-O2 -fomit-frame-pointer -m68040` will use mulu again since it's faster.
```
_foo:
        move.l d2,-(sp)
        move.l 8(sp),d2
        jsr _faa
        mulu.w #320,d2
        and.l #65535,d0
        add.l d2,d0
        move.l (sp)+,d2
        rts
```
> This is all C++ code and the functions mentioned above are member functions.

you might consider  `__regargs`

> Could there be any compiler switch that would allow me to say "In case of speed try to optimize for 030, but still don't use functions not available on 060"?

there is only `-m68020-60` the option `-m68030-60` does not exist. And since there is no one working to improve the timings no one will create that new switch.

**Comment by mheyer32** [comment]
Thanks for confirmation!
I knew about the issues with pushing bytes to the stack, but I thought that the CPU will 'realign' byte sized stack pushes... Anyway, I'd be not concerned with ABI incompatibilities, since there's no such thing as existing .a, .so's or DLLs to be compatible with. Interfacing .library's is totally different anyway.

I do now use __regargs for a few specific functions, but I'm not sure if that does more harm than good(?)
True, the called function itself does not need to take things off the stack, but the callsite may have more  trouble shuffling things around to end up in the right register. I also needed some experimentation to find the right number of register arguments to get the smallest number of instructions.

WRT mulu: I have switched over to hand-tune the functions to use shifts for mulu in a few places, guided by gprof.
Is there a way to specify the target architecture (030/060) as a temporary pragma around the functions instead? This way I don't have to touch the code itself and the compiler will still have some more freedom.

For ScummVM I'd really like to use -Os (it brings down the executable size by ca 1MB!), but the loss in speed is considerable. I have not identified the optimization that most increases the executable size... I guess its function inlining. Ideally, I'd like to find a middle ground between size and speed.

**Comment by bebbo** [comment]
> Anyway, I'd be not concerned with ABI incompatibilities, ...

Well, there is no universal approach for best parameter passing since it depends on the parameter usage of the function too^^ 
... and I better don't touch the short/long behaviour

> WRT mulu: I have switched over to hand-tune the functions to use shifts for mulu in a few places, guided by gprof.

The better way is to tell, which is not suitable on the 68060 or what's done wrong.
Maybe it's time to start hacking gcc yourself!? My guess that providing more correct instuction costs (aka cycles) would lead to better code. So there is only one function to hack: `m68k_rtx_costs` in the `gcc/config/m68k` folder. And if you add `-fbbb=+V` you can read the calculated insn costs in the assembly source.

> For ScummVM I'd really like to use -Os (it brings down the executable size by ca 1MB!), but the loss in speed is considerable. 

the optimization for speeds start more early and stuff is done different which cannot be modified by other  options. Maybe -O2 or -O1 plus adding some desired optimizations is a feasable approach.

**Comment by mheyer32** [comment]
If we turn that statement around and check the TUNE_COST for the lowly 68k's first, it might just do what I want. I'll give it a go when I got some time. Thanks for the pointer.

> Maybe it's time to start hacking gcc yourself!?

I am aware that I have been asking for a lot lately; the gcc code has such a discouragingly steep ramp up and I have only a fuzzy idea on how it works...

**Comment by bebbo** [comment]
I modifed the costs calculation...
... imho better, but who knows^^ :-)

so what's the plan with this ticket?

**Comment by mheyer32** [comment]
Lets close it. I have not come around toying with the TUNE macros for mulu yet :-(

I still think, when enabling a range of processors, it would be best to optimize for the slowest in that range. 
I.e. when enabling 68020-60, make it fast for the 020 and assume it'll be 'fast enough' on the 060 anyways. If we compile for 060 only, we can pull off every trick the 060 has up its sleeves.

**Comment by bebbo** [comment]
> I.e. when enabling 68020-60, make it fast for the 020 and assume it'll be 'fast enough' on the 060 anyways. If we compile for 060 only, we can pull off every trick the 060 has up its sleeves.

current interpretation is
```
-m68020-40                  Generate code for a 68040, without any new
                              instructions.
```
which means also optimize for 68040.

-m68020 will always run on better processors. So if you wan't it tuned for 68020, use `-m68020`
