### ISSUE TITLE
Compiler crash when compiling ADoom

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#75]
Something broke the build at https://github.com/mheyer32/ADoom :

```
amiga_median.c: In function 'median_cut':
amiga_median.c:237:1: error: unrecognizable insn:
 }
 ^
(insn 794 1289 795 81 (set (reg/v:HI 373 [ i ])
        (zero_extend:HI (mem:QI (plus:SI (plus:SI (reg:SI 378 [ _477 ])
                        (reg/v:SI 374 [ primary ]))
                    (reg:SI 1047)) [1 MEM[symbol: node, base: _477, index: primary_688, offset: 0B]+0 S1 A8]))) amiga_median.c:96 -1
     (nil))
amiga_median.c:237:1: internal compiler error: in extract_insn, at recog.c:2293
```

**Comment by mheyer32** [comment]
This is triggered by -O3 and -Ofast, even with -fbbb=-

**Comment by bebbo** [comment]
on Linux:
```
adoom_src]$ date; make clean -j >& /dev/null; make -j >& /dev/null; date; ll ADoom
Tue Feb 26 16:34:32 CET 2019
Tue Feb 26 16:34:33 CET 2019
-rwxrwxr-x. 1 stefan stefan 3350632 Feb 26 16:34 ADoom
```

**Comment by mheyer32** [comment]
Bebbo,  did you retract your "can't reproduce"?

**Comment by bebbo** [comment]
yes :-)

these versions (by date) are still building adoom:
 - 2019-02-07 
 - 2019-02-15

Did you know that you can use
 - `make v` checkout recent version
 - `make v date=<date>` checkout version for date <date> 
always checkout the recent version before going to a specific date.

**Comment by bebbo** [comment]
building 2019-02-17 atm - takes 12 mins each...

**Comment by bebbo** [comment]
I suspect 55f69ef652d1afd797eb3a4bb485098a6414ea69 which is not the direct cause but made it happen

**Comment by mheyer32** [comment]
Not sure if you know 'git bisect' - it can help quite a lot in such cases.

Will  'make v date=<date>' restore each of the sub-repos to the given date? Thats neat!

**Comment by bebbo** [comment]
> Will 'make v date=' restore each of the sub-repos to the given date? Thats neat!
yes, it does. Your starting version needs to be in the future. `make v` switches to the HEAD of each.

**Comment by githubaf** [comment]
Make v date sounds cool!I currently use my own script for that...Is that a new feature?Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: bebbo <notifications@github.com> Datum: 26.02.19  20:30  (GMT+01:00) An: bebbo/gcc <gcc@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [bebbo/gcc] Compiler crash when compiling ADoom (#75) 
Will 'make v date=' restore each of the sub-repos to the given date? Thats neat!
yes, it does. Your starting version needs to be in the future. make v switches to the HEAD of each.


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bebbo/gcc","title":"bebbo/gcc","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bebbo/gcc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bebbo in #75: \u003e Will 'make v date=' restore each of the sub-repos to the given date? Thats neat!\r\nyes, it does. Your starting version needs to be in the future. `make v` switches to the HEAD of each."}],"action":{"name":"View Issue","url":"https://github.com/bebbo/gcc/issues/75#issuecomment-467578845"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bebbo/gcc/issues/75#issuecomment-467578845",
"url": "https://github.com/bebbo/gcc/issues/75#issuecomment-467578845",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bebbo** [comment]
> I suspect 55f69ef which is not the direct cause but made it happen
confirmed

> Make v date sounds cool!I currently use my own script for that...Is that a new feature?
it's not too old^^

**Comment by bebbo** [comment]
please test

**Comment by mheyer32** [comment]
Adoom compiles again, but doesn't link anymore due to 
https://github.com/bebbo/libnix/commit/ce1ba64e130c3dfafdc60639e5d74636504a99d1

I'll file a separate issue for that.
