### ISSUE TITLE
calling asm functions passing parameters by registers from C++

### ISSUE THREAD

**Issue by pellicus** [bebbo/gcc#77]
Hi Bebbo!
I found around this syntax to pass parameters specifying registers name, I know it works on gcc 3.4.0
long add( register long a __asm("d0"), register long b __asm("d1") );

I miss the right syntax in gcc 6.  probably some __attribute__ or something similar but I was not able to find out a solution googling around :/

Thanks for the hint and for your great work!!!

**Comment by githubaf** [comment]
Look forgcc extended asmSyntax. That works and is in fact quite cool as is selects registers automatically. So it integrates asm into c and avoids unnecessary register moves.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Dario Pelella <notifications@github.com> Datum: 02.03.19  15:29  (GMT+01:00) An: bebbo/gcc <gcc@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [bebbo/gcc] calling asm functions passing parameters by registers from C++ (#77) Hi Bebbo!
I found around this syntax to pass parameters specifying registers name, I know it works on gcc 3.4.0
long add( register long a __asm("d0"), register long b __asm("d1") );
I miss the right syntax in gcc 6.  probably some attribute or something similar but I was not able to find out a solution googling around :/
Thanks for the hint and for your great work!!!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bebbo/gcc","title":"bebbo/gcc","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bebbo/gcc"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"calling asm functions passing parameters by registers from C++ (#77)"}],"action":{"name":"View Issue","url":"https://github.com/bebbo/gcc/issues/77"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bebbo/gcc/issues/77",
"url": "https://github.com/bebbo/gcc/issues/77",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bebbo** [comment]
se #66

**Comment by bebbo** [comment]
please test
